### ISSUE TITLE
Sequences of key combos are subject to noise from REAL inputs  being re-exerted over and over

### ISSUE THREAD

**Issue by joshgoebel** [joshgoebel/keyszer#45]
When I used Shift or Ctrl as part of the shortcut, your branch is failing in the same way as the Kinto branch when doing a Unicode macro. It exits the Unicode entry mode after the first character, then outputs the final three characters of the Unicode address. I'm suspecting that somehow the Unicode entry is getting interrupted by receiving a release event for Shift or Ctrl when I lift the associated physical shortcut keys. 

_Originally posted by @RedBearAK in https://github.com/joshgoebel/keyszer/issues/43#issuecomment-1160331625_

**Comment by joshgoebel** [comment]
This is largely resolved if one uses `timeouts(suspend=1)` which makes sure the REAL keys are often never sent to the output at all - so they can't mess anything up... but if you hold them too long, or use a low suspend then the keys DO get exerted on output - and the engine with press/release them over and over before/after every combo that is a sequence of combos.

Of course this will break many types of complex key entry like Unicode entry systems.

**Comment by RedBearAK** [comment]
> @RedBearAK If you could test this PR and confirm it indeed fixes your issue with the work you're attempting on Unicode support...

That appears to have fixed the Unicode macro, at least in brief testing. Even changed the input shortcut to have both Shift and RC (and Alt) and it seems to work OK regardless of how rapidly or slowly I release any of the keys involved. 

But my Cmd+clicking seems to not be working as expected anymore, even though I left the `suspend` at 0.1 in my config. Appears I need to hold Cmd for about a second now, before clicking. Yeah, that's totally breaking my text selection with Shift+click, also. 

I feel like it's time to talk about a true "key down until end of combo/macro sequence, then release" kind of latch directive, that will just block release events (not sure about repeats) until they should be allowed. I was about to try a `bind` directive to see if that would make any difference, but I suspect not. Possibly if one of the keys is held during the whole macro entry sequence, but not if all keys are released too quickly. If I'm thinking about it correctly.

**Comment by joshgoebel** [comment]
> But my Cmd+clicking seems to not be working as expected anymore, 

Are you using `timeouts` API?

```
timeouts(
    multipurpose = 1,
    suspend = 0.1,
)
```

**Comment by joshgoebel** [comment]
> I feel like it's time to talk about a true "key down until end of combo/macro sequence

For what purpose?

I'm not sure why you'd want bind for your unicode stuff... I wasn't aware it required holding down keys...

**Comment by joshgoebel** [comment]
Merged.

**Comment by RedBearAK** [comment]
Yes, I have this block right near the top of my config file now. It was working fine before the new pull. 

```
# Keyszer-specific config settings
dump_diagnostics_key(Key.F7)
emergency_eject_key(Key.F8)
timeouts(
    multipurpose = 1,
    suspend = 0.1,
)
```

> For what purpose?

For blocking the release events (or possibly repeat events) that seem to be breaking the Unicode entry mode. 

When I was doing the Alt Code method with AHK I had to mimic the way Windows wants you to hold Alt and use Numpad keys to type the Alt Code, then release Alt only at the end. AHK has things like `{Alt down}` and `{Alt up}` for that kind of situation. 

> I'm not sure why you'd want bind for your unicode stuff... I wasn't aware it required holding down keys...

No, it didn't work. Well, there is the other method where you do hold down Shift+Ctrl+u and then release all three after typing the Unicode address (no Enter key in that case). But the method I'm trying to use doesn't require holding the first combo, just triggering it and then using the Enter key at the end to complete the sequence.

**Comment by joshgoebel** [comment]
> blocking the release events (or possibly repeat events) that seem to be breaking the Unicode entry mode.

I thought my PR fixed unicode entry?  The issue is all the extraneous press/release activity that is generated, which the PR fixes.

---

> It was working fine before the new pull.

Pretty sure it has nothing to do with the PR... has got to be something else... Are you using a multi-modmap?

**Comment by joshgoebel** [comment]
And please confirm you're having troubles on the latest main, e8d9fe09050d7ea7618155b19322d85fce574223

**Comment by RedBearAK** [comment]
> I thought my PR fixed unicode entry? The issue is all the extraneous press/release activity that is generated between sequential combos, which the PR fixes.

It does fix the Unicode macros. But breaks my short suspend timeout. Apparently. Can't tell you why. 

I think I'm actually thinking of a solution slightly different from the explicit "key down, key up" latches. More like a "ignore these modifiers until end of sequence, after first momentary trigger of combo" kind of thing. It would have to be able to be applied only to the specific combo, so it wouldn't affect the rest of the macro sequence, other than blocking further events from the keys in that combo. Does this not make any sense? 

> Pretty sure it has nothing to do with the PR... has got to be something else... Are you using a multi-modmap?

My config file didn't change from before the pull, other than changing one of the Unicode macro shortcuts afterward to include Shift and RC, to make sure the fix worked with those keys. It does. 

The only multipurpose modmap is this thing that's always been commented out. This is related to some Kinto tweak options, I think. I've never used them. 

```
define_multipurpose_modmap(
    # {Key.ENTER: [Key.ENTER, Key.RIGHT_CTRL]   # Enter2Cmd
    # {Key.CAPSLOCK: [Key.ESC, Key.RIGHT_CTRL]  # Caps2Esc
    # {Key.LEFT_META: [Key.ESC, Key.RIGHT_CTRL] # Caps2Esc - Chromebook
    {                                         # Placeholder
})
```

**Comment by joshgoebel** [comment]
> But breaks my short suspend timeout.

Literally nothing around that changed though. 🙁 Ha, `timeouts` NEVER worked... fixed in cc2c69d

**Comment by joshgoebel** [comment]
> Does this not make any sense?

Nope, as always real, actual examples are best.

**Comment by RedBearAK** [comment]
Does this look right? I feel like the last couple of pulls hasn't actually pulled any new lines into main. 

```
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0
Unpacking objects: 100% (5/5), 1.04 KiB | 107.00 KiB/s, done.
From https://github.com/joshgoebel/keyszer
   e381e9d..cc2c69d  xorg_errors -> origin/xorg_errors
Already up to date.
```

**Comment by joshgoebel** [comment]
Just look at `git log`... and compare it to github.

**Comment by RedBearAK** [comment]
From the description of the earlier commit I think you've already done what I was describing anyway. 

I seem to be up to date but I'm definitely still having the issue with the short suspend timeout not being applied. 

Is there a simple "git rewind" kind of thing to peel off the last few commits that have been applied?

**Comment by RedBearAK** [comment]
WTHeck. I did a `git reset` back to an earlier commit that was definitely before the Unicode fix, and that didn't fix the timeout, but then I just stashed and did another `git pull` to get back to current main, and suddenly the shortened timeout seems to be respected again. AND the Unicode macro shortcuts are still working. 

Absolutely no idea.

**Comment by joshgoebel** [comment]
> and suddenly the shortened timeout seems to be respected again. AND the Unicode macro shortcuts are still working.

Because I fixed it all. :)

**Comment by joshgoebel** [comment]
> Is there a simple "git rewind" kind of thing to peel off the last few commits that have been applied?

You can checkout any revision you want with `git checkout sha`....
